// ═══════════════════════════════════════════
// Mock Data for Edu-expert Platform
// Used during development without Supabase
// ═══════════════════════════════════════════

export const WILAYAS = [
    { id: 1, name_ar: 'أدرار', name_fr: 'Adrar', code: '01' },
    { id: 2, name_ar: 'الشلف', name_fr: 'Chlef', code: '02' },
    { id: 3, name_ar: 'الأغواط', name_fr: 'Laghouat', code: '03' },
    { id: 4, name_ar: 'أم البواقي', name_fr: 'Oum El Bouaghi', code: '04' },
    { id: 5, name_ar: 'باتنة', name_fr: 'Batna', code: '05' },
    { id: 6, name_ar: 'بجاية', name_fr: 'Béjaïa', code: '06' },
    { id: 7, name_ar: 'بسكرة', name_fr: 'Biskra', code: '07' },
    { id: 8, name_ar: 'بشار', name_fr: 'Béchar', code: '08' },
    { id: 9, name_ar: 'البليدة', name_fr: 'Blida', code: '09' },
    { id: 10, name_ar: 'البويرة', name_fr: 'Bouira', code: '10' },
    { id: 15, name_ar: 'تيزي وزو', name_fr: 'Tizi Ouzou', code: '15' },
    { id: 16, name_ar: 'الجزائر', name_fr: 'Alger', code: '16' },
    { id: 17, name_ar: 'الجلفة', name_fr: 'Djelfa', code: '17' },
    { id: 19, name_ar: 'سطيف', name_fr: 'Sétif', code: '19' },
    { id: 23, name_ar: 'عنابة', name_fr: 'Annaba', code: '23' },
    { id: 25, name_ar: 'قسنطينة', name_fr: 'Constantine', code: '25' },
    { id: 31, name_ar: 'وهران', name_fr: 'Oran', code: '31' },
    { id: 34, name_ar: 'برج بوعريريج', name_fr: 'Bordj Bou Arréridj', code: '34' },
    { id: 35, name_ar: 'بومرداس', name_fr: 'Boumerdès', code: '35' },
    { id: 42, name_ar: 'تيبازة', name_fr: 'Tipaza', code: '42' },
];

export const BALADIYAS = [
    { id: 1601, wilaya_id: 16, name_ar: 'الجزائر الوسطى', name_fr: 'Alger Centre' },
    { id: 1602, wilaya_id: 16, name_ar: 'باب الزوار', name_fr: 'Bab Ezzouar' },
    { id: 1603, wilaya_id: 16, name_ar: 'بن عكنون', name_fr: 'Ben Aknoun' },
    { id: 1604, wilaya_id: 16, name_ar: 'حيدرة', name_fr: 'Hydra' },
    { id: 1605, wilaya_id: 16, name_ar: 'الشراقة', name_fr: 'Chéraga' },
    { id: 3101, wilaya_id: 31, name_ar: 'وهران', name_fr: 'Oran' },
    { id: 3102, wilaya_id: 31, name_ar: 'السانية', name_fr: 'Es Sénia' },
    { id: 2501, wilaya_id: 25, name_ar: 'قسنطينة', name_fr: 'Constantine' },
    { id: 901, wilaya_id: 9, name_ar: 'البليدة', name_fr: 'Blida' },
    { id: 1901, wilaya_id: 19, name_ar: 'سطيف', name_fr: 'Sétif' },
    { id: 501, wilaya_id: 5, name_ar: 'باتنة', name_fr: 'Batna' }
];

export const INSTITUTION_TYPES = [
    { id: 1, name_ar: 'روضة أطفال', name_fr: 'Crèche / Jardin d\'enfants', icon: '🧒', color: '#F472B6' },
    { id: 2, name_ar: 'مدرسة ابتدائية', name_fr: 'École Primaire', icon: '📚', color: '#60A5FA' },
    { id: 3, name_ar: 'متوسطة', name_fr: 'CEM (Collège)', icon: '🏫', color: '#34D399' },
    { id: 4, name_ar: 'ثانوية', name_fr: 'Lycée', icon: '🎓', color: '#A78BFA' },
    { id: 5, name_ar: 'جامعة', name_fr: 'Université', icon: '🏛️', color: '#F59E0B' },
    { id: 6, name_ar: 'مركز تكوين مهني', name_fr: 'Centre de Formation Professionnelle', icon: '⚙️', color: '#F97316' },
    { id: 7, name_ar: 'مدرسة خاصة', name_fr: 'École Privée', icon: '⭐', color: '#EC4899' },
    { id: 8, name_ar: 'مدرسة قرآنية', name_fr: 'École Coranique', icon: '🕌', color: '#14B8A6' },
];

export const MOCK_INSTITUTIONS = [
        id: 'mock-inst-1', // Changed to string ID for consistency
        name_ar: 'مدرسة النخبة العالمية',
        name_fr: 'Elite International School',
        type_id: 5,
        logo_url: '/mockups/school_logo.png',
        wilaya_id: 16,
        baladiya_id: 1601,
        city_ar: 'الجزائر العاصمة',
        city_fr: 'Alger Centre',
        address_ar: '12 شارع الإخوة بوعدو، الأبيار',
        address_fr: '12 Rue Frères Bouadou, El Biar',
        lat: 36.7642, // El Biar coordinates
        lng: 3.0298,
        phone: '021 00 11 22',
        email: 'contact@elite-school.dz',
        website: '',
        description_ar: 'مدرسة رائدة توفر تعليمًا عصريًا ببرامج دولية متميزة.',
        description_fr: 'Une école pionnière offrant une éducation moderne avec d\'excellents programmes internationaux.',
        rating: 4.8,
        reviews_count: 42,
        students_count: 850,
        status: 'approved',
        images: [],
        programs_ar: ['ابتدائي', 'متوسط', 'ثانوي (لغات، علوم)'],
        programs_fr: ['Primaire', 'Moyen', 'Secondaire (Langues, Sciences)'],
    },
    {
        id: 'mock-inst-2',
        name_ar: 'مركز التدريب التقني',
        name_fr: 'Tech Training Center',
        type_id: 6,
        wilaya_id: 31,
        baladiya_id: 3102,
        city_ar: 'بير الجير',
        city_fr: 'Bir El Djir',
        address_ar: 'حي الياسمين، وهران',
        address_fr: 'Cité Yasmine, Oran',
        lat: 35.7289, // Bir El Djir coordinates
        lng: -0.5516,
        phone: '041 55 66 77',
        email: 'info@tech-center.dz',
        website: '',
        description_ar: 'نخبة من الأساتذة والخبراء لتدريب الشباب على أحدث التقنيات.',
        description_fr: 'Le meilleur des professeurs et experts pour former les jeunes aux dernières technologies.',
        rating: 4.5,
        reviews_count: 18,
        students_count: 320,
        status: 'approved',
        images: [],
        programs_ar: ['برمجة', 'تصميم جرافيك', 'لغات حية'],
        programs_fr: ['Programmation', 'Design Graphique', 'Langues Vivantes'],
    },
    {
        id: 1,
    {
        id: 2,
        name_ar: 'جامعة هواري بومدين للعلوم والتكنولوجيا',
        name_fr: 'USTHB - Université des Sciences et de la Technologie Houari Boumédiène',
        type_id: 5,
        wilaya_id: 16,
        baladiya_id: 1602,
        city_ar: 'باب الزوار',
        city_fr: 'Bab Ezzouar',
        address_ar: 'باب الزوار، الجزائر',
        address_fr: 'BP 32, El Alia, Bab Ezzouar, Alger',
        lat: 36.7100,
        lng: 3.1735,
        phone: '+213 21 24 79 50',
        email: 'contact@usthb.dz',
        website: 'https://www.usthb.dz',
        description_ar: 'جامعة هواري بومدين للعلوم والتكنولوجيا (USTHB) هي أكبر جامعة في الجزائر من حيث عدد الطلبة. متخصصة في العلوم والتكنولوجيا.',
        description_fr: 'L\'USTHB est la plus grande université d\'Algérie en termes d\'effectifs étudiants. Spécialisée en sciences et technologie.',
        rating: 4.0,
        reviews_count: 256,
        students_count: 55000,
        status: 'approved',
        images: [],
        programs_ar: ['إعلام آلي', 'رياضيات', 'فيزياء', 'كيمياء', 'بيولوجيا', 'جيولوجيا'],
        programs_fr: ['Informatique', 'Mathématiques', 'Physique', 'Chimie', 'Biologie', 'Géologie'],
    },
    {
        id: 3,
        name_ar: 'ثانوية الأمير عبد القادر',
        name_fr: 'Lycée Emir Abdelkader',
        type_id: 4,
        wilaya_id: 16,
        baladiya_id: 1603,
        city_ar: 'بن عكنون',
        city_fr: 'Ben Aknoun',
        address_ar: 'بن عكنون، الجزائر',
        address_fr: 'Ben Aknoun, Alger',
        lat: 36.7600,
        lng: 3.0100,
        phone: '+213 21 91 34 56',
        email: 'lycee.abdelkader@edu.dz',
        website: '',
        description_ar: 'ثانوية الأمير عبد القادر من أعرق الثانويات في العاصمة. تقدم شعب العلوم التجريبية والرياضيات والآداب والفلسفة.',
        description_fr: 'Le Lycée Emir Abdelkader est l\'un des plus prestigieux lycées de la capitale. Il offre les filières Sciences Expérimentales, Mathématiques et Lettres et Philosophie.',
        rating: 4.5,
        reviews_count: 87,
        students_count: 1200,
        status: 'approved',
        images: [],
        programs_ar: ['علوم تجريبية', 'رياضيات', 'تقني رياضي', 'آداب وفلسفة', 'لغات أجنبية'],
        programs_fr: ['Sciences Expérimentales', 'Mathématiques', 'Technique Mathématiques', 'Lettres et Philosophie', 'Langues Étrangères'],
    },
    {
        id: 4,
        name_ar: 'متوسطة حسيبة بن بوعلي',
        name_fr: 'CEM Hassiba Ben Bouali',
        type_id: 3,
        wilaya_id: 31,
        baladiya_id: 3101,
        city_ar: 'وهران',
        city_fr: 'Oran',
        address_ar: 'حي المنصورة، وهران',
        address_fr: 'Cité El Mansourah, Oran',
        lat: 35.6971,
        lng: -0.6308,
        phone: '+213 41 23 45 67',
        email: 'cem.hassiba@edu.dz',
        website: '',
        description_ar: 'متوسطة حسيبة بن بوعلي تقع في قلب مدينة وهران. تتميز بنتائجها الممتازة في شهادة التعليم المتوسط.',
        description_fr: 'Le CEM Hassiba Ben Bouali est situé au cœur d\'Oran. Il se distingue par ses excellents résultats au BEM.',
        rating: 4.3,
        reviews_count: 45,
        students_count: 800,
        status: 'approved',
        images: [],
        programs_ar: [],
        programs_fr: [],
    },
    {
        id: 5,
        name_ar: 'مدرسة النجاح الابتدائية',
        name_fr: 'École Primaire En-Najah',
        type_id: 2,
        wilaya_id: 25,
        baladiya_id: 2501,
        city_ar: 'قسنطينة',
        city_fr: 'Constantine',
        address_ar: 'حي زيغود يوسف، قسنطينة',
        address_fr: 'Cité Zighoud Youcef, Constantine',
        lat: 36.3650,
        lng: 6.6147,
        phone: '+213 31 87 65 43',
        email: 'ecolenajah@edu.dz',
        website: '',
        description_ar: 'مدرسة النجاح الابتدائية مؤسسة عريقة في مدينة قسنطينة. توفر بيئة تعليمية ممتازة للأطفال من السنة الأولى إلى السنة الخامسة ابتدائي.',
        description_fr: 'L\'École En-Najah est un établissement de longue date à Constantine. Elle offre un excellent environnement éducatif pour les enfants de la 1ère à la 5ème année primaire.',
        rating: 4.6,
        reviews_count: 32,
        students_count: 500,
        status: 'approved',
        images: [],
        programs_ar: [],
        programs_fr: [],
    },
    {
        id: 6,
        name_ar: 'المعهد الوطني للتكوين المهني',
        name_fr: 'INSFP - Institut National Spécialisé de Formation Professionnelle',
        type_id: 6,
        wilaya_id: 9,
        baladiya_id: 901,
        city_ar: 'البليدة',
        city_fr: 'Blida',
        address_ar: 'شارع الاستقلال، البليدة',
        address_fr: 'Rue de l\'Indépendance, Blida',
        lat: 36.4722,
        lng: 2.8278,
        phone: '+213 25 43 21 09',
        email: 'insfp.blida@mfep.gov.dz',
        website: '',
        description_ar: 'المعهد الوطني المتخصص في التكوين المهني بالبليدة يقدم تكوينات في الإعلام الآلي، الإلكترونيك، والمحاسبة.',
        description_fr: 'L\'INSFP de Blida offre des formations en Informatique, Électronique et Comptabilité.',
        rating: 3.8,
        reviews_count: 21,
        students_count: 600,
        status: 'approved',
        images: [],
        programs_ar: ['إعلام آلي', 'إلكترونيك', 'محاسبة', 'سكرتارية'],
        programs_fr: ['Informatique', 'Électronique', 'Comptabilité', 'Secrétariat'],
    },
    {
        id: 7,
        name_ar: 'روضة الأمل',
        name_fr: 'Crèche El-Amel',
        type_id: 1,
        wilaya_id: 16,
        baladiya_id: 1604,
        city_ar: 'حيدرة',
        city_fr: 'Hydra',
        address_ar: 'حي حيدرة، الجزائر العاصمة',
        address_fr: 'Cité Hydra, Alger',
        lat: 36.7450,
        lng: 3.0320,
        phone: '+213 21 60 12 34',
        email: 'creche.elamel@gmail.com',
        website: '',
        description_ar: 'روضة الأمل توفر بيئة آمنة ومحفّزة للأطفال من سن 3 إلى 6 سنوات. برامج تعليمية وترفيهية متنوعة.',
        description_fr: 'La Crèche El-Amel offre un environnement sûr et stimulant pour les enfants de 3 à 6 ans. Programmes éducatifs et récréatifs variés.',
        rating: 4.7,
        reviews_count: 19,
        students_count: 80,
        status: 'approved',
        images: [],
        programs_ar: ['تعليم أولي', 'لعب تربوي', 'تحفيظ قرآن'],
        programs_fr: ['Éducation Préscolaire', 'Jeux Éducatifs', 'Mémorisation du Coran'],
    },
    {
        id: 8,
        name_ar: 'جامعة سطيف 1 - فرحات عباس',
        name_fr: 'Université Sétif 1 - Ferhat Abbas',
        type_id: 5,
        wilaya_id: 19,
        baladiya_id: 1901,
        city_ar: 'سطيف',
        city_fr: 'Sétif',
        address_ar: 'المجمع الجامعي، الماوكلي، سطيف',
        address_fr: 'Campus Universitaire, El Maabouda, Sétif',
        lat: 36.1914,
        lng: 5.4134,
        phone: '+213 36 92 51 27',
        email: 'contact@univ-setif.dz',
        website: 'https://www.univ-setif.dz',
        description_ar: 'جامعة فرحات عباس سطيف 1 من أكبر الجامعات في الشرق الجزائري. تضم كليات العلوم والهندسة والطب.',
        description_fr: 'L\'Université Ferhat Abbas Sétif 1 est l\'une des plus grandes universités de l\'est algérien. Elle comprend les facultés de Sciences, Ingénierie et Médecine.',
        rating: 3.9,
        reviews_count: 190,
        students_count: 38000,
        status: 'approved',
        images: [],
        programs_ar: ['طب', 'صيدلة', 'هندسة مدنية', 'إعلام آلي', 'بيولوجيا'],
        programs_fr: ['Médecine', 'Pharmacie', 'Génie Civil', 'Informatique', 'Biologie'],
    },
    {
        id: 9,
        name_ar: 'مدرسة الريادة الخاصة',
        name_fr: 'École Privée El-Riyada',
        type_id: 7,
        wilaya_id: 16,
        baladiya_id: 1605,
        city_ar: 'الشراقة',
        city_fr: 'Chéraga',
        address_ar: 'حي الياسمين، الشراقة',
        address_fr: 'Cité El Yasmine, Chéraga',
        lat: 36.7620,
        lng: 2.9550,
        phone: '+213 21 37 89 01',
        email: 'info@ecole-riyada.dz',
        website: 'https://www.ecole-riyada.dz',
        description_ar: 'مدرسة الريادة الخاصة تقدم برنامج تعليمي متميز يجمع بين المنهاج الوطني والبرامج الدولية. تعليم بثلاث لغات.',
        description_fr: 'L\'École El-Riyada offre un programme éducatif distingué combinant le programme national et les programmes internationaux. Enseignement trilingue.',
        rating: 4.8,
        reviews_count: 15,
        students_count: 350,
        status: 'approved',
        images: [],
        programs_ar: ['ابتدائي', 'متوسط', 'برنامج دولي'],
        programs_fr: ['Primaire', 'Moyen', 'Programme International'],
    },
    {
        id: 10,
        name_ar: 'جامعة وهران 1 - أحمد بن بلة',
        name_fr: 'Université Oran 1 - Ahmed Ben Bella',
        type_id: 5,
        wilaya_id: 31,
        baladiya_id: 3101,
        city_ar: 'وهران',
        city_fr: 'Oran',
        address_ar: 'المجمع الجامعي، السانية، وهران',
        address_fr: 'Campus Universitaire, Es-Sénia, Oran',
        lat: 35.6500,
        lng: -0.5830,
        phone: '+213 41 51 92 22',
        email: 'contact@univ-oran1.dz',
        website: 'https://www.univ-oran1.dz',
        description_ar: 'جامعة وهران 1 أحمد بن بلة من أكبر الجامعات في الغرب الجزائري. تتميز بكلياتها العلمية والأدبية.',
        description_fr: 'L\'Université Oran 1 Ahmed Ben Bella est l\'une des plus grandes universités de l\'ouest algérien.',
        rating: 4.1,
        reviews_count: 167,
        students_count: 42000,
        status: 'approved',
        images: [],
        programs_ar: ['طب', 'قانون', 'علوم اقتصادية', 'لغات', 'فيزياء'],
        programs_fr: ['Médecine', 'Droit', 'Sciences Économiques', 'Langues', 'Physique'],
    },
    {
        id: 11,
        name_ar: 'مدرسة ابن خلدون القرآنية',
        name_fr: 'École Coranique Ibn Khaldoun',
        type_id: 8,
        wilaya_id: 25,
        baladiya_id: 2501,
        city_ar: 'قسنطينة',
        city_fr: 'Constantine',
        address_ar: 'المدينة القديمة، قسنطينة',
        address_fr: 'Vieille Ville, Constantine',
        lat: 36.3700,
        lng: 6.6200,
        phone: '+213 31 94 56 78',
        email: 'ibnkhaldoun.ecole@gmail.com',
        website: '',
        description_ar: 'مدرسة ابن خلدون القرآنية مؤسسة عريقة متخصصة في تحفيظ القرآن الكريم وتعليم العلوم الشرعية.',
        description_fr: 'L\'École Coranique Ibn Khaldoun est un établissement spécialisé dans la mémorisation du Coran et l\'enseignement des sciences islamiques.',
        rating: 4.9,
        reviews_count: 42,
        students_count: 200,
        status: 'approved',
        images: [],
        programs_ar: ['تحفيظ القرآن', 'علوم شرعية', 'لغة عربية'],
        programs_fr: ['Mémorisation du Coran', 'Sciences Islamiques', 'Langue Arabe'],
    },
    {
        id: 12,
        name_ar: 'ثانوية العقيد لطفي - باتنة',
        name_fr: 'Lycée Colonel Lotfi - Batna',
        type_id: 4,
        wilaya_id: 5,
        baladiya_id: 501,
        city_ar: 'باتنة',
        city_fr: 'Batna',
        address_ar: 'وسط المدينة، باتنة',
        address_fr: 'Centre Ville, Batna',
        lat: 35.5560,
        lng: 6.1740,
        phone: '+213 33 86 54 32',
        email: 'lycee.lotfi.batna@edu.dz',
        website: '',
        description_ar: 'ثانوية العقيد لطفي من أعرق الثانويات في ولاية باتنة. تتميز بنتائجها في البكالوريا.',
        description_fr: 'Le Lycée Colonel Lotfi est l\'un des plus anciens lycées de Batna, reconnu pour ses résultats au baccalauréat.',
        rating: 4.4,
        reviews_count: 56,
        students_count: 1500,
        status: 'approved',
        images: [],
        programs_ar: ['علوم تجريبية', 'رياضيات', 'تقني رياضي', 'تسيير واقتصاد'],
        programs_fr: ['Sciences Expérimentales', 'Mathématiques', 'Technique Math', 'Gestion et Économie'],
    },
];

// ─────────────────────────────────────────────────────────────────────
// MOCK ANNOUNCEMENTS
// ─────────────────────────────────────────────────────────────────────
export const MOCK_ANNOUNCEMENTS = [
    {
        id: 'mock-ann-1',
        institution_id: 'mock-inst-1',
        title_ar: 'بدء التسجيلات للسنة الدراسية 2026/2027',
        title_fr: 'Inscriptions Ouvertes 2026/2027',
        content_ar: 'يسرنا أن نعلن لأولياء الأمور عن بدء استقبال ملفات التسجيل لجميع الأطوار التعليمية.',
        content_fr: 'Nous avons le plaisir d\'annoncer l\'ouverture des inscriptions pour l\'année scolaire 2026/2027.',
        created_at: new Date().toISOString(),
        registration_open: true,
        institutions: { name_ar: 'مدرسة النخبة العالمية', name_fr: 'Elite International School' }
    },
    {
        id: 'mock-ann-2',
        institution_id: 'mock-inst-2',
        title_ar: 'يوم مفتوح للتعريف بالمدرسة',
        title_fr: 'Journée Portes Ouvertes',
        content_ar: 'ندعوكم لحضور اليوم المفتوح يوم السبت القادم للتعرف على مرافق المدرسة.',
        content_fr: 'Rejoignez-nous samedi prochain pour découvrir nos installations.',
        created_at: new Date().toISOString(),
        registration_open: false,
        institutions: { name_ar: 'مركز التدريب التقني', name_fr: 'Tech Training Center' }
    }
];

// ─────────────────────────────────────────────────────────────────────
// MOCK PRODUCTS (BOOKS)
// ─────────────────────────────────────────────────────────────────────
export const MOCK_BOOKS = [
    {
        id: 'mock-book-1',
        name: 'الرياضيات الممتعة - السنة الأولى ابتدائي',
        author: 'أ. سليم منصوري',
        price: 850,
        discount_price: 790,
        status: 'active',
        description: 'كتاب تفاعلي متميز لتبسيط الرياضيات للأطفال بطرق حديثة ومبسطة.',
        cover_url: '/mockups/math_cover.png',
        rating_avg: 4.8
    },
    {
        id: 'mock-book-2',
        name: 'الطريق إلى النجاح في البكالوريا - فيزياء',
        author: 'أ. كمال بن علي',
        price: 1200,
        status: 'active',
        description: 'شرح وافٍ لجميع دروس الفيزياء مع تمارين محلولة ونماذج اختبارات سابقة.',
        cover_url: null,
        rating_avg: 4.5
    },
    {
        id: 'mock-book-3',
        name: 'رواية: عابر سبيل',
        author: 'للكاتبة مريم فرح',
        price: 1400,
        discount_price: 1150,
        status: 'active',
        description: 'رواية أدبية معاصرة تأخذك في رحلة مشوقة عبر تاريخ وزوايا الجزائر الجميلة.',
        cover_url: '/mockups/novel_cover.png',
        rating_avg: 4.9
    }
];

export const MOCK_STATS = {
    totalInstitutions: 12847,
    totalWilayas: 58,
    totalReviews: 34521,
    totalUsers: 156780,
    pendingInstitutions: 23,
    approvedToday: 5,
};
